[tool.poetry]
name = "scientific computing"
version = "0.1.0"
description = ""
authors = ["lordPachy <francescocalzona03@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "^3.10"
numpy = "^2.2.4"
matplotlib = "^3.10.1"
=======
python = "^3.12"
>>>>>>> cec26a5 (Fem)
ipykernel = "^6.29.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
